name: ROS2 jazzy CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy-ros-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |              
          apt update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build package
        run: |
          . /opt/ros/jazzy/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Run tests
        run: |
          . /opt/ros/jazzy/setup.bash
          colcon test
          colcon test-result --verbose
