name: ROS2 jazzy CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |              
          apt update && apt install -y curl gnupg lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc \
          | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
          http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" \
          > /etc/apt/sources.list.d/ros2.list
          apt update
          apt-get install -y python3-colcon-common-extensions　python3-rosdep
          rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Run tests
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test
          colcon test-result --verbose
