name: ROS2 jazzy CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions　python3-rosdep
          rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Run tests
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test
          colcon test-result --verbose
